# Generated by Django 6.0.4 on 2026-04-28 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExporterAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_email', models.EmailField(max_length=254, unique=True)),
                ('main_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('is_domain_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exporter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
