# Generated by Django 6.0.4 on 2026-04-28 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExporterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('product_list_sku', models.TextField(blank=True, help_text='Product List (SKU)', null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('target_region', models.CharField(blank=True, help_text='Region / Country', max_length=255, null=True)),
                ('buyer_type', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_channel', models.CharField(blank=True, help_text='E.g., Email, LinkedIn, WhatsApp', max_length=255, null=True)),
                ('language_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('spf_verified', models.BooleanField(default=False)),
                ('dkim_verified', models.BooleanField(default=False)),
                ('dmarc_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='exporter.exporteraccount')),
            ],
        ),
    ]
