# Generated by Django 6.0.2 on 2026-04-28 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0003_exporteraccount_exporter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporteraccount',
            name='exporter_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
